application:
  port: 8000
database:
  host: "localhost"
  port: 5432
  username: "didadadida93"
  database_name: "didadadida93"
email_client:
  base_url: "localhost"
  sender_email: "test@gmail.com"
  authorization_token: "my-secret-token"
